# Generated by Django 3.1.5 on 2021-03-25 02:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('freepile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='comment',
            table='comment',
        ),
    ]
